image: node:14.15.1 # change to match your project's node version

stages: 
 - build
 - deploy 

cache:
  paths:
    - node_modules/

pages:
  stage: build
    script: 
    - rm -rf build
    - CI=false npm install
    - CI=false npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
    artifacts:
      paths:
      - public
  stage: deploy
    script:
     - ls
   artifacts:
     paths:
      - public
 
